### ISSUE TITLE
[새기능] yml 파일 구현

### ISSUE THREAD

**Issue by noahmik** [TeamPLOY/Bubble_Server_v3#1]
### ✨ 개요

db, email 인증, security 설정을 위한 yml 파일들을 구현하고, 기본 파일 구조를 정의합니다.

### ✅ 해야 할 일

- [x] application.yml 구현
- [x] application-db.yml 구현
- [x] application-security.yml 구현
- [x] application-email.yml 구현
- [x] 필요한 의존성 추가
- [x] 기본 파일 구조 정의

### 🙋🏻 덧붙일 말

환경 별로 yml를 분리하는 것도 고려해보면 좋을꺼 같습니다.

**Comment by kangsiwoo** [comment]
그에게 주어지는 머지 목걸이
