### ISSUE TITLE
[새기능] 라이브러리 사용을 위한 Config 설정

### ISSUE THREAD

**Issue by noahmik** [TeamPLOY/Bubble_Server_v3#9]
### ✨ 개요

이 설정 파일은 API 문서화 및 보안 관련 라이브러리를 사용하기 위한 Config를 설정합니다

### ✅ 해야 할 일

- [x] JpaConfig 설정
- [x] RestTemplateClient 설정
- [x] SecurityConfig 설정
- [x] SwaggerConfig 설정
- [x] 필요한 의존성 추가

### 🙏🏻 요구사항

- [x] 테스트 코드를 작성합니다.. 제발

### 🙋🏻 덧붙일 말

코드 나오는거 맞아요? asap으로 해주세요

**Comment by kangsiwoo** [comment]
코틀린 레퍼런스 한번씩 정독하고 코딩하면 더 좋은 코틀린 코드가 나올 수 있을것같아요!

**Comment by noahmik** [comment]
넵 알겠습니다 !
